- name: Create/Add/Delete Network Security Groups
  hosts: localhost
  connection: local
  tasks:
  - name: A50-Network Security Group
    azure_rm_securitygroup:
      resource_group: A50-Network-RG
      name: A50-Network-NIC-NSG
      state: present # Set to <present> to create or update a security group. Set to <absent> to remove a security group
      tags: # enter '*' relevant tags
      rules:
        - name: AzureLoadBalancerHealthCheck_Inbound
          priority: 1000
          destination_port_range: '*'
          protocol: '*'
          source_address_prefix: AzureLoadBalancer
          destination_address_prefix: '*'
          access: Allow
          direction: Inbound
        - name: OnPremises_RDP-Inbound
          priority: 1001
          destination_port_range: 3389
          protocol: '*'
          source_address_prefix: 10.0.0.0/10
          destination_address_prefix: '*'
          access: Allow
          direction: Inbound
        - name: ActiveDirectory_LDAP_Inbound
          priority: 1002
          destination_port_range: 389
          protocol: '*'
          source_address_prefix: '*'
          destination_address_prefix: '*'
          access: Allow
          direction: Inbound
