- name: Create/Add/Delete Network Security Groups
  hosts: localhost
  connection: local
  tasks:
  - name: EUS1-TRANSIT-FW1 Untrust Subnet Security Group
    azure_rm_securitygroup:
      resource_group: EUS1-TRANSIT-VNET-RG
      name: EUS1-Untrust-Subnet-NSG
      state: present # Set to <present> to create or update a security group. Set to <absent> to remove a security group
      location: East US
      tags:
        Environment: Production
        Geo: EUS1
        Entity: Technology
        Type: Infrastructure
        Team: Network
      rules:
        - name: AzureLoadBalancerHealthCheck_Inbound
          priority: 1000
          destination_port_range: '*'
          protocol: '*'
          source_address_prefix: AzureLoadBalancer
          destination_address_prefix: '*'
          access: Allow
          direction: Inbound
        - name: HTTPS_Inbound
          priority: 1001
          destination_port_range: 443
          protocol: 'Tcp'
          source_address_prefix: 1.1.1.1/24
          destination_address_prefix: '*'
          access: Allow
          direction: Inbound
        - name: HTTPS_Inbound
          priority: 1002
          destination_port_range: '443'
          protocol: 'Tcp'
          source_address_prefix: 1.1.1.1/24
          destination_address_prefix: '*'
          access: Allow
          direction: Inbound
